version: '3.8'
services:
  mysql:
    image: mysql:8.0.41-debian
    container_name: smart-travel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smart_travel_db
    ports:
      - "3306:3306"
    volumes:
      - smart-travel-mysql-data:/var/lib/mysql
    networks:
      - smart-travel-network


volumes:
  smart-travel-mysql-data:

networks:
  smart-travel-network:
    driver: bridge

