// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvsnD_3_Sa-1qQBqx3hDBx_3Lky9NXLCU',
    appId: '1:905844988595:web:7bcb9aa28b1779e3bd6ec6',
    messagingSenderId: '905844988595',
    projectId: 'travelapp-6af12',
    authDomain: 'travelapp-6af12.firebaseapp.com',
    storageBucket: 'travelapp-6af12.firebasestorage.app',
    measurementId: 'G-MWN7WL95P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo0EMs54ZyXfka9iBDZybqXcd2vC4hw_o',
    appId: '1:905844988595:android:786bb25f8dc99b87bd6ec6',
    messagingSenderId: '905844988595',
    projectId: 'travelapp-6af12',
    storageBucket: 'travelapp-6af12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6lrZrHrRLtQEPgKKi-iNyngKIB9kC2Pw',
    appId: '1:905844988595:ios:860ff0fa1914832cbd6ec6',
    messagingSenderId: '905844988595',
    projectId: 'travelapp-6af12',
    storageBucket: 'travelapp-6af12.firebasestorage.app',
    androidClientId: '905844988595-rocfvug12f8bjgo09u2fcuqu8emg1nh4.apps.googleusercontent.com',
    iosClientId: '905844988595-0259psb26pjba2pm6cgh6h7sj8k1gncd.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6lrZrHrRLtQEPgKKi-iNyngKIB9kC2Pw',
    appId: '1:905844988595:ios:860ff0fa1914832cbd6ec6',
    messagingSenderId: '905844988595',
    projectId: 'travelapp-6af12',
    storageBucket: 'travelapp-6af12.firebasestorage.app',
    androidClientId: '905844988595-rocfvug12f8bjgo09u2fcuqu8emg1nh4.apps.googleusercontent.com',
    iosClientId: '905844988595-0259psb26pjba2pm6cgh6h7sj8k1gncd.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvsnD_3_Sa-1qQBqx3hDBx_3Lky9NXLCU',
    appId: '1:905844988595:web:cbedeb1c25e0badcbd6ec6',
    messagingSenderId: '905844988595',
    projectId: 'travelapp-6af12',
    authDomain: 'travelapp-6af12.firebaseapp.com',
    storageBucket: 'travelapp-6af12.firebasestorage.app',
    measurementId: 'G-EV1TS2CWBK',
  );
}
