server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: smart-travel

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION}

gemini:
  api:
    key: ${GEMINI_API_KEY}

huggingface:
  api:
    key: ${HUGGINGFACE_API_KEY}

deepseek:
  api:
    key: ${DEEPSEEK_API_KEY}

ai:
  service:
    url: ${AI_SERVICE_URL}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}